spring:
  application:
    name: webmagic
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://[MYSQL-IP]:3306/spider?characterEncoding=utf-8&amp&serverTimezone=Asia/Shanghai&amp&useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  jackson:
    time-zone: GMT+8
    locale: zh_CN
    date-format: yyyy-MM-dd
    serialization:
      indent_output: true
      fail_on_empty_beans: false
    defaultPropertyInclusion: NON_NULL
    deserialization:
      fail_on_unknown_properties: false
      accept_single_value_as_array: true
    parser:
      allow_unquoted_control_chars: true
      allow_single_quotes: true
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
  redis:
    host: [REDIS-IP]
    database: 0
    password:
    port: 6379
  task:
    scheduling:
      rule:
        bilibili: "*/4 * 0 * * *"
        zhihu: "*/7 * 0 * * *"
        baidu: "0 2 0 * * *"
        weibo: "*/5 * * * * *"
        doulist: "*/5 * * * * *"
    spider:
      delay: 0
    execution:
      pool:
        allow-core-thread-timeout: on
        max-size: 15
        queue-capacity: 15

server:
  port: 18080
  servlet:
    context-path: /webmagic

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.example.webmagic: debug
    com:
      alibaba:
        nacos: warn

output:
  file-path-prefix:
    bilibili: data
    zhihu: data
    baidu: data
    douban: data
    weibo: data